version: '3.8'

services:
  my-api-services:
    
    container_name: rfid-attendance-container
    image: my-api
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:16.2-alpine
    container_name: rfid_postgres
    restart: always
    ports:
      - "5432:5432"
    command: postgres -c max_wal_senders=2 -c wal_level=logical -c max_replication_slots=2
    env_file: .env

    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:


