version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rfid_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: rfid_attendance
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
