// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package my_queries

import (
	"context"
	"database/sql"

	"github.com/ronishg27/rfid_attendance/internal/models/tenant"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMember(db *gorm.DB, opts ...gen.DOOption) member {
	_member := member{}

	_member.memberDo.UseDB(db, opts...)
	_member.memberDo.UseModel(&tenant.Member{})

	tableName := _member.memberDo.TableName()
	_member.ALL = field.NewAsterisk(tableName)
	_member.ID = field.NewString(tableName, "id")
	_member.Name = field.NewString(tableName, "name")
	_member.Email = field.NewString(tableName, "email")
	_member.Phone = field.NewString(tableName, "phone")
	_member.Role = field.NewString(tableName, "role")
	_member.IsActive = field.NewBool(tableName, "is_active")
	_member.RFIDUID = field.NewString(tableName, "rf_id_uid")
	_member.Department = field.NewString(tableName, "department")
	_member.Status = field.NewString(tableName, "status")
	_member.ExpectedCheckIn = field.NewString(tableName, "expected_check_in")
	_member.ExpectedCheckOut = field.NewString(tableName, "expected_check_out")
	_member.CreatedAt = field.NewTime(tableName, "created_at")
	_member.UpdatedAt = field.NewTime(tableName, "updated_at")

	_member.fillFieldMap()

	return _member
}

type member struct {
	memberDo

	ALL              field.Asterisk
	ID               field.String
	Name             field.String
	Email            field.String
	Phone            field.String
	Role             field.String
	IsActive         field.Bool
	RFIDUID          field.String
	Department       field.String
	Status           field.String
	ExpectedCheckIn  field.String
	ExpectedCheckOut field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (m member) Table(newTableName string) *member {
	m.memberDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m member) As(alias string) *member {
	m.memberDo.DO = *(m.memberDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *member) updateTableName(table string) *member {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.Name = field.NewString(table, "name")
	m.Email = field.NewString(table, "email")
	m.Phone = field.NewString(table, "phone")
	m.Role = field.NewString(table, "role")
	m.IsActive = field.NewBool(table, "is_active")
	m.RFIDUID = field.NewString(table, "rf_id_uid")
	m.Department = field.NewString(table, "department")
	m.Status = field.NewString(table, "status")
	m.ExpectedCheckIn = field.NewString(table, "expected_check_in")
	m.ExpectedCheckOut = field.NewString(table, "expected_check_out")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *member) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *member) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["email"] = m.Email
	m.fieldMap["phone"] = m.Phone
	m.fieldMap["role"] = m.Role
	m.fieldMap["is_active"] = m.IsActive
	m.fieldMap["rf_id_uid"] = m.RFIDUID
	m.fieldMap["department"] = m.Department
	m.fieldMap["status"] = m.Status
	m.fieldMap["expected_check_in"] = m.ExpectedCheckIn
	m.fieldMap["expected_check_out"] = m.ExpectedCheckOut
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m member) clone(db *gorm.DB) member {
	m.memberDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m member) replaceDB(db *gorm.DB) member {
	m.memberDo.ReplaceDB(db)
	return m
}

type memberDo struct{ gen.DO }

type IMemberDo interface {
	gen.SubQuery
	Debug() IMemberDo
	WithContext(ctx context.Context) IMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemberDo
	WriteDB() IMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemberDo
	Not(conds ...gen.Condition) IMemberDo
	Or(conds ...gen.Condition) IMemberDo
	Select(conds ...field.Expr) IMemberDo
	Where(conds ...gen.Condition) IMemberDo
	Order(conds ...field.Expr) IMemberDo
	Distinct(cols ...field.Expr) IMemberDo
	Omit(cols ...field.Expr) IMemberDo
	Join(table schema.Tabler, on ...field.Expr) IMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemberDo
	Group(cols ...field.Expr) IMemberDo
	Having(conds ...gen.Condition) IMemberDo
	Limit(limit int) IMemberDo
	Offset(offset int) IMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberDo
	Unscoped() IMemberDo
	Create(values ...*tenant.Member) error
	CreateInBatches(values []*tenant.Member, batchSize int) error
	Save(values ...*tenant.Member) error
	First() (*tenant.Member, error)
	Take() (*tenant.Member, error)
	Last() (*tenant.Member, error)
	Find() ([]*tenant.Member, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*tenant.Member, err error)
	FindInBatches(result *[]*tenant.Member, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*tenant.Member) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemberDo
	Assign(attrs ...field.AssignExpr) IMemberDo
	Joins(fields ...field.RelationField) IMemberDo
	Preload(fields ...field.RelationField) IMemberDo
	FirstOrInit() (*tenant.Member, error)
	FirstOrCreate() (*tenant.Member, error)
	FindByPage(offset int, limit int) (result []*tenant.Member, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memberDo) Debug() IMemberDo {
	return m.withDO(m.DO.Debug())
}

func (m memberDo) WithContext(ctx context.Context) IMemberDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memberDo) ReadDB() IMemberDo {
	return m.Clauses(dbresolver.Read)
}

func (m memberDo) WriteDB() IMemberDo {
	return m.Clauses(dbresolver.Write)
}

func (m memberDo) Session(config *gorm.Session) IMemberDo {
	return m.withDO(m.DO.Session(config))
}

func (m memberDo) Clauses(conds ...clause.Expression) IMemberDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memberDo) Returning(value interface{}, columns ...string) IMemberDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memberDo) Not(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memberDo) Or(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memberDo) Select(conds ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memberDo) Where(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memberDo) Order(conds ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memberDo) Distinct(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memberDo) Omit(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memberDo) Join(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memberDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemberDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memberDo) Group(cols ...field.Expr) IMemberDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memberDo) Having(conds ...gen.Condition) IMemberDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memberDo) Limit(limit int) IMemberDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memberDo) Offset(offset int) IMemberDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemberDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memberDo) Unscoped() IMemberDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memberDo) Create(values ...*tenant.Member) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memberDo) CreateInBatches(values []*tenant.Member, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memberDo) Save(values ...*tenant.Member) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memberDo) First() (*tenant.Member, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*tenant.Member), nil
	}
}

func (m memberDo) Take() (*tenant.Member, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*tenant.Member), nil
	}
}

func (m memberDo) Last() (*tenant.Member, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*tenant.Member), nil
	}
}

func (m memberDo) Find() ([]*tenant.Member, error) {
	result, err := m.DO.Find()
	return result.([]*tenant.Member), err
}

func (m memberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*tenant.Member, err error) {
	buf := make([]*tenant.Member, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memberDo) FindInBatches(result *[]*tenant.Member, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memberDo) Attrs(attrs ...field.AssignExpr) IMemberDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memberDo) Assign(attrs ...field.AssignExpr) IMemberDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memberDo) Joins(fields ...field.RelationField) IMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memberDo) Preload(fields ...field.RelationField) IMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memberDo) FirstOrInit() (*tenant.Member, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*tenant.Member), nil
	}
}

func (m memberDo) FirstOrCreate() (*tenant.Member, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*tenant.Member), nil
	}
}

func (m memberDo) FindByPage(offset int, limit int) (result []*tenant.Member, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memberDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memberDo) Delete(models ...*tenant.Member) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memberDo) withDO(do gen.Dao) *memberDo {
	m.DO = *do.(*gen.DO)
	return m
}
